version: '3.8'

volumes:
  database:
  static_value:
  media_value:

services:
  db:
    container_name: yamdb_db_dev
    image: postgres:15.1-alpine
    volumes:
      - database:/var/lib/postgresql/data/
    env_file:
      - ./.env

  web:
    container_name: yamdb_web_dev
    image: vorvorsky/api_yamdb:v1.02
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    container_name: yamdb_nginx_dev
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default_dev.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - web