version: '3.8'

volumes:
  database:
  static_value:
  media_value:
  certbot-etc:
  web-root:

services:
  db:
    container_name: yamdb_db
    image: postgres:15.1-alpine
    volumes:
      - database:/var/lib/postgresql/data/
    env_file:
      - ./.env

  web:
    container_name: yamdb_web
    image: vorvorsky/api_yamdb:v1.02
    restart: always
    volumes:
      - static_value:/app/api_yamdb/static/
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    container_name: yamdb_nginx
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_value:/app/api_yamdb/static/
      - web-root:/var/html/www
      - certbot-etc:/etc/letsencrypt
    depends_on:
      - web

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - web-root:/var/html/www
      - certbot-etc:/etc/letsencrypt
    depends_on:
      - nginx
    command: certonly --webroot --webroot-path=/var/html/www --email ${EMAIL} --agree-tos --no-eff-email --force-renewal -d ${DOMAIN}
    env_file:
      - ./.env
